steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/devto-project/deploy-nestjs-api-to-cloud-run",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/devto-project/deploy-nestjs-api-to-cloud-run"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "api-blog1",
        "--image",
        "gcr.io/devto-project/deploy-nestjs-api-to-cloud-run",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--port",
        "3000",
      ]
images:
  - gcr.io/devto-project/deploy-nestjs-api-to-cloud-run
